# -*- coding: utf-8 -*-
"""bubbleSort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXwAMDKOw1RjynB_4LKJNE_b7RfSc5Bv
"""

#bubble sort
array = [10,50,60,30,80]
print("Here your original array:\n")
print(array)

def bubbleSort(arr):
  n=len(arr)
  for i in range(n-1):
    swapped = False
    for j in range(n-i-1):
      if arr[j] > arr[j+1]:
        arr[j] , arr[j+1] =  arr[j+1] , arr[j]
        swapped = True

    if not swapped:
      break

    print()

bubbleSort(array)

print("Here your sorted array:\n")
print(array)

