# -*- coding: utf-8 -*-
"""insertionSort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXwAMDKOw1RjynB_4LKJNE_b7RfSc5Bv
"""

# insertion  sort
# Data = 22, 10, 26, 8, 5

def insertionSort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1

        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key

arr = [12, 11, 13, 5, 6]
insertionSort(arr)
print(arr)